//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapaBobs.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public decimal SmallSize { get; set; }
        public decimal MediumSize { get; set; }
        public decimal LargeSize { get; set; }
        public decimal RegularCrust { get; set; }
        public decimal ThinCurst { get; set; }
        public decimal ThickCurst { get; set; }
        public decimal Sausage { get; set; }
        public decimal Pepperoni { get; set; }
        public decimal Onions { get; set; }
        public decimal GreenPeppers { get; set; }
    }
}
